# name: CI tester

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     #runs-on: ubuntu-latest
#     runs-on: ubuntu-s-1vcpu-2gb-sgp1-01
    
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       # - uses: actions/checkout@v4

#       # - name: Set up Node.js
#       #   uses: actions/setup-node@v2
#       #   with:
#       #     node-version: ${{ matrix.node-version }}

#       # - name: Install dependencies
#       #   run: npm install

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: whoami

      
        
#       - name: create file
#         run: touch ~/test_file_hari_minggu.txt

#       - name: check file
#         run: ls -l test_file.txt
#       - name: lokasi file
#         run: pwd
#       #- name: check python version
#        # run: python --version

#       #- name: check pip version
#         #run: pip --version

#       #- name: check pip packages
#        # run: pip show requests

#       #- name: check installed package
#        # run: pip list
        
#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: cd ~ | ls -l




name: Test Python, Node.js, and Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, node, go]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        if: matrix.language == 'python'
        run: |
          pytest  # Or your preferred test command

      - name: Set up Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        if: matrix.language == 'node'
        run: npm ci

      - name: Run Node.js tests
        if: matrix.language == 'node'
        run: npm test

      - name: Set up Go
        if: matrix.language == 'go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Go tests
        if: matrix.language == 'go'
        run: go test ./...
